development:
  adapter: postgresql
  encoding: unicode
  database: hello_rails_development
  pool: 5
  host: localhost
  username: oliver
  password: 123456

test:
  adapter: postgresql
  encoding: unicode
  database: hello_rails_test
  pool: 5
  username: oliver
  password: 123456

staging:
  url: <%= ENV['DATABASE_URL'] %>

production:
  url: <%= ENV['DATABASE_URL'] %> 